[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda/", "conda-forge"]
description = "Add a short description here"
name = "tabby"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-tabby = "bash scripts/install-tabby.sh"
install-ipex-ollama = "bash scripts/install-ipex-ollama.sh"

[dependencies]
wget = ">=1.21.4,<2"
unzip = ">=6.0,<7"
cmake = ">=3.30.5,<4"
c-compiler = ">=1.8.0,<2"
cxx-compiler = ">=1.8.0,<2"
python = "3.11.*"
pip = ">=24.3.1,<24.4"

[activation]
scripts = ["env.sh"]
