[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tabby"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-tabby = "bash scripts/install-tabby.sh"
create = "bash scripts/create-distrobox.sh"
enter = "bash scripts/enter-distrobox.sh"

[dependencies]
wget = ">=1.21.4,<2"
unzip = ">=6.0,<7"

[activation]
scripts = ["env.sh"]
